# Generated by Django 4.1.2 on 2022-10-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('residuos', models.CharField(max_length=50)),
            ],
        ),
    ]
