# Generated by Django 4.1.2 on 2022-11-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuarios_delete_principal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='info',
        ),
    ]
