# Generated by Django 4.1.2 on 2022-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_usuarios_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Emisor'), (2, 'Remitente')])),
                ('ubicacion', models.IntegerField(choices=[(1, 'Arica y Parinacota'), (2, 'Tarapacá'), (3, 'Antofagasta'), (4, 'Atacama'), (5, 'Coquimbo'), (6, 'Valparaíso'), (7, 'Metropolitana'), (8, 'Libertador General Bernardo OHiggins'), (9, 'Maule'), (10, 'Biobío'), (11, 'Araucanía'), (12, 'Los Ríos'), (13, 'Los Lagos'), (14, 'Aysén'), (15, 'Emisor'), (16, 'Magallanes')])),
                ('residuos', models.IntegerField(choices=[(1, 'Plástico'), (2, 'Latas'), (3, 'Residuos Orgánicos'), (4, 'Residuos Metalicos'), (5, 'Ropa/Tela'), (6, 'Cartón'), (7, 'Vidrios'), (8, 'Madera'), (9, 'Papel'), (10, 'Baterías y pilas'), (11, 'Chatarra'), (12, 'Otros')])),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='empresa',
            field=models.CharField(max_length=20),
        ),
    ]
