# Generated by Django 4.1.2 on 2022-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_select_alter_info_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='ubicacion',
            field=models.IntegerField(choices=[(1, 'Arica y Parinacota'), (2, 'Tarapacá'), (3, 'Antofagasta'), (4, 'Atacama'), (5, 'Coquimbo'), (6, 'Valparaíso'), (7, 'Metropolitana'), (8, 'Libertador General Bernardo OHiggins'), (9, 'Maule'), (10, 'Ñuble'), (11, 'Biobío'), (12, 'Araucanía'), (13, 'Los Ríos'), (14, 'Los Lagos'), (15, 'Aysén'), (16, 'Magallanes')]),
        ),
    ]
