# Generated by Django 4.1.2 on 2022-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_select_ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='select',
        ),
        migrations.AddField(
            model_name='info',
            name='residuos',
            field=models.IntegerField(choices=[(1, 'Plástico'), (2, 'Latas'), (3, 'Residuos Orgánicos'), (4, 'Residuos Metalicos'), (5, 'Ropa/Tela'), (6, 'Cartón'), (7, 'Vidrios'), (8, 'Madera'), (9, 'Papel'), (10, 'Baterías y pilas'), (11, 'Chatarra'), (12, 'Otros')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Emisor'), (2, 'Remitente')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='ubicacion',
            field=models.IntegerField(choices=[(1, 'Arica y Parinacota'), (2, 'Tarapacá'), (3, 'Antofagasta'), (4, 'Atacama'), (5, 'Coquimbo'), (6, 'Valparaíso'), (7, 'Metropolitana'), (8, 'Libertador General Bernardo OHiggins'), (9, 'Maule'), (10, 'Ñuble'), (11, 'Biobío'), (12, 'Araucanía'), (13, 'Los Ríos'), (14, 'Los Lagos'), (15, 'Aysén'), (16, 'Magallanes')], default=0),
            preserve_default=False,
        ),
    ]
