# Generated by Django 4.1.2 on 2022-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_select_info_residuos_info_tipo_info_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='empresa',
            field=models.CharField(max_length=50),
        ),
    ]
